In [8]:

# ## Anaconda가 설치 업데이트
# !conda update conda -y
# !conda update --all -y

import pandas as pd
print(pd.__version__)

3.0.5

In [11]:
loan_df = pd.read_csv('data/loan.csv')
display(loan_df)

,loan_id,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
0,LP1003,Y,N,4583,128.4,Rural,N
1,LP1005,Y,Y,3000,66.0,City,Y
2,LP1006,Y,N,2583,120.5,City,Y
3,LP1008,N,N,6000,141.4,City,Y
4,LP1011,Y,Y,5417,267.4,City,Y
...,...,...,...,...,...,...,...
595,LP2974,Y,N,3232,108.6,Rural,Y
596,LP2979,Y,N,4106,40.7,Rural,Y
597,LP2983,Y,N,8072,253.4,City,Y
598,LP2984,Y,N,7583,187.6,City,Y
599,LP2990,N,Y,4583,133.2,Suburb,N

In [12]:
loan_df.head() #기본 5줄

,loan_id,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
0,LP1003,Y,N,4583,128.4,Rural,N
1,LP1005,Y,Y,3000,66.0,City,Y
2,LP1006,Y,N,2583,120.5,City,Y
3,LP1008,N,N,6000,141.4,City,Y
4,LP1011,Y,Y,5417,267.4,City,Y

In [ ]:
loan_df.tail() #뒤에서 5줄

,loan_id,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
595,LP2974,Y,N,3232,108.6,Rural,Y
596,LP2979,Y,N,4106,40.7,Rural,Y
597,LP2983,Y,N,8072,253.4,City,Y
598,LP2984,Y,N,7583,187.6,City,Y
599,LP2990,N,Y,4583,133.2,Suburb,N

In [14]:
loan_df.shape

(600, 7)

In [19]:
loan_df.dtypes

loan_id                     str
married_or_not              str
self_employed_or_not        str
applicant_income          int64
loan_amount             float64
property_area               str
loan_status                 str
dtype: object

In [21]:
loan_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   loan_id               600 non-null    str
 1   married_or_not        600 non-null    str
 2   self_employed_or_not  568 non-null    str
 3   applicant_income      600 non-null    int64
 4   loan_amount           589 non-null    float64
 5   property_area         600 non-null    str
 6   loan_status           600 non-null    str
dtypes: float64(1), int64(1), str(5)
memory usage: 41.2 KB

In [23]:
loan_df.describe()

       applicant_income  loan_amount
count        600.000000   589.000000
mean        5412.161667   146.971307
std         6160.362669    85.756442
min          150.000000     9.200000
25%         2880.500000   100.700000
50%         3806.000000   128.000000
75%         5785.000000   168.300000
max        81000.000000   700.300000

In [24]:
loan_df.describe(include='all')

,loan_id,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
count,600,600,568,600.000000,589.000000,600,600
unique,600,2,2,NaN,NaN,3,2
top,LP1003,Y,N,NaN,NaN,Suburb,Y
freq,1,390,488,NaN,NaN,228,408
mean,NaN,NaN,NaN,5412.161667,146.971307,NaN,NaN
std,NaN,NaN,NaN,6160.362669,85.756442,NaN,NaN
min,NaN,NaN,NaN,150.000000,9.200000,NaN,NaN
25%,NaN,NaN,NaN,2880.500000,100.700000,NaN,NaN
50%,NaN,NaN,NaN,3806.000000,128.000000,NaN,NaN
75%,NaN,NaN,NaN,5785.000000,168.300000,NaN,NaN
max,NaN,NaN,NaN,81000.000000,700.300000,NaN,NaN

In [ ]:
loan_df.sort_values(by='loan_amount' )

,loan_id,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
555,LP2840,N,N,2378,9.2,City,N
13,LP1030,Y,N,1299,17.5,City,Y
91,LP1325,N,N,3620,25.0,Suburb,Y
125,LP1482,Y,Y,3459,25.3,Suburb,Y
542,LP2792,Y,N,5468,26.5,Suburb,Y
...,...,...,...,...,...,...,...
377,LP2243,Y,N,3010,NaN,City,N
467,LP2533,Y,N,2947,NaN,City,N
512,LP2697,N,N,4680,NaN,Suburb,N
538,LP2778,Y,Y,6633,NaN,Rural,N
592,LP2960,Y,N,2400,NaN,City,N

In [26]:
loan_df.sort_values(by='loan_amount', ascending=False)

,loan_id,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
163,LP1585,Y,N,51763,700.3,City,Y
122,LP1469,N,Y,20166,650.2,City,Y
548,LP2813,Y,Y,19484,600.4,Suburb,Y
147,LP1536,Y,N,39999,600.0,Suburb,Y
359,LP2191,Y,N,19730,570.1,Rural,N
...,...,...,...,...,...,...,...
377,LP2243,Y,N,3010,NaN,City,N
467,LP2533,Y,N,2947,NaN,City,N
512,LP2697,N,N,4680,NaN,Suburb,N
538,LP2778,Y,Y,6633,NaN,Rural,N
592,LP2960,Y,N,2400,NaN,City,N

In [2]:
## 엑셀 파일 불러오기
import pandas as pd
#기본 1번째 시트
load_excel_df = pd.read_excel('data/loan.xlsx')

#2번째 시트 명시
load_excel_df = pd.read_excel('data/loan.xlsx', sheet_name=1) #2번째 시트

load_excel_df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,loan_id,married,self_employed,applicant_income,loan_amount,property_area,loan_status
3,NaN,LP1003,Y,N,4583,128,Rural,N
4,NaN,LP1005,Y,Y,3000,66,City,Y
...,...,...,...,...,...,...,...,...
598,NaN,LP2974,Y,N,3232,108,Rural,Y
599,NaN,LP2979,Y,N,4106,40,Rural,Y
600,NaN,LP2983,Y,N,8072,253,City,Y
601,NaN,LP2984,Y,N,7583,187,City,Y
602,NaN,LP2990,N,Y,4583,133,Suburb,N

In [3]:
#2번째 시트 B열부터 H열에 있는 데이터를 가져오기
load_excel_df = pd.read_excel('data/loan.xlsx', sheet_name=1, header=3, usecols='B:H')
load_excel_df

,loan_id,married,self_employed,applicant_income,loan_amount,property_area,loan_status
0,LP1003,Y,N,4583,128.0,Rural,N
1,LP1005,Y,Y,3000,66.0,City,Y
2,LP1006,Y,N,2583,120.0,City,Y
3,LP1008,N,N,6000,141.0,City,Y
4,LP1011,Y,Y,5417,267.0,City,Y
...,...,...,...,...,...,...,...
595,LP2974,Y,N,3232,108.0,Rural,Y
596,LP2979,Y,N,4106,40.0,Rural,Y
597,LP2983,Y,N,8072,253.0,City,Y
598,LP2984,Y,N,7583,187.0,City,Y
599,LP2990,N,Y,4583,133.0,Suburb,N