In [23]:
import pandas as pd

loan_df = pd.read_csv('data/loan.csv')
loan_df

,loan_id,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
0,LP1003,Y,N,4583,128.4,Rural,N
1,LP1005,Y,Y,3000,66.0,City,Y
2,LP1006,Y,N,2583,120.5,City,Y
3,LP1008,N,N,6000,141.4,City,Y
4,LP1011,Y,Y,5417,267.4,City,Y
...,...,...,...,...,...,...,...
595,LP2974,Y,N,3232,108.6,Rural,Y
596,LP2979,Y,N,4106,40.7,Rural,Y
597,LP2983,Y,N,8072,253.4,City,Y
598,LP2984,Y,N,7583,187.6,City,Y
599,LP2990,N,Y,4583,133.2,Suburb,N

# 인덱스 설정, 리셋, 
# 컬럼 이름 변경
# 컬럼 타입 변경

In [24]:
##df 기본 제공 숫자가 아닌 컬럼중에 인덱스 선언
loan_df.set_index('loan_id')

,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
loan_id,,,,,,
LP1003,Y,N,4583,128.4,Rural,N
LP1005,Y,Y,3000,66.0,City,Y
LP1006,Y,N,2583,120.5,City,Y
LP1008,N,N,6000,141.4,City,Y
LP1011,Y,Y,5417,267.4,City,Y
...,...,...,...,...,...,...
LP2974,Y,N,3232,108.6,Rural,Y
LP2979,Y,N,4106,40.7,Rural,Y
LP2983,Y,N,8072,253.4,City,Y
LP2984,Y,N,7583,187.6,City,Y
LP2990,N,Y,4583,133.2,Suburb,N

In [26]:
loan_df 
## 업데이트 하지 않았기에 변화지 않음

,loan_id,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
0,LP1003,Y,N,4583,128.4,Rural,N
1,LP1005,Y,Y,3000,66.0,City,Y
2,LP1006,Y,N,2583,120.5,City,Y
3,LP1008,N,N,6000,141.4,City,Y
4,LP1011,Y,Y,5417,267.4,City,Y
...,...,...,...,...,...,...,...
595,LP2974,Y,N,3232,108.6,Rural,Y
596,LP2979,Y,N,4106,40.7,Rural,Y
597,LP2983,Y,N,8072,253.4,City,Y
598,LP2984,Y,N,7583,187.6,City,Y
599,LP2990,N,Y,4583,133.2,Suburb,N

In [27]:
loan_df = loan_df.set_index('loan_id')
display(loan_df)

,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
loan_id,,,,,,
LP1003,Y,N,4583,128.4,Rural,N
LP1005,Y,Y,3000,66.0,City,Y
LP1006,Y,N,2583,120.5,City,Y
LP1008,N,N,6000,141.4,City,Y
LP1011,Y,Y,5417,267.4,City,Y
...,...,...,...,...,...,...
LP2974,Y,N,3232,108.6,Rural,Y
LP2979,Y,N,4106,40.7,Rural,Y
LP2983,Y,N,8072,253.4,City,Y
LP2984,Y,N,7583,187.6,City,Y
LP2990,N,Y,4583,133.2,Suburb,N

In [29]:
loan_df = loan_df.reset_index() ## 인덱스 초기화
display(loan_df)

,loan_id,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
0,LP1003,Y,N,4583,128.4,Rural,N
1,LP1005,Y,Y,3000,66.0,City,Y
2,LP1006,Y,N,2583,120.5,City,Y
3,LP1008,N,N,6000,141.4,City,Y
4,LP1011,Y,Y,5417,267.4,City,Y
...,...,...,...,...,...,...,...
595,LP2974,Y,N,3232,108.6,Rural,Y
596,LP2979,Y,N,4106,40.7,Rural,Y
597,LP2983,Y,N,8072,253.4,City,Y
598,LP2984,Y,N,7583,187.6,City,Y
599,LP2990,N,Y,4583,133.2,Suburb,N

In [ ]:
#loan_df = loan_df.set_index('loan_id')
### 컬럼명 변경
loan_df.columns

Index(['married_or_not', 'self_employed_or_not', 'applicant_income',
       'loan_amount', 'property_area', 'loan_status'],
      dtype='str')

In [45]:
loan_df.columns = ['married', 'self_employed', 'applicant_income',
       'loan_amount', 'property_area', 'loan_status']
loan_df.columns

Index(['married', 'self_employed', 'applicant_income', 'loan_amount',
       'property_area', 'loan_status'],
      dtype='str')

In [47]:
##특정 컬러만 변경 시 --> dict {} 이용
new_columns = { 'applicant_income': 'income', 'loan_amount': 'amount' }
loan_df.rename(columns = new_columns)

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N    4583   128.4         Rural           N
LP1005        Y             Y    3000    66.0          City           Y
LP1006        Y             N    2583   120.5          City           Y
LP1008        N             N    6000   141.4          City           Y
LP1011        Y             Y    5417   267.4          City           Y
...         ...           ...     ...     ...           ...         ...
LP2974        Y             N    3232   108.6         Rural           Y
LP2979        Y             N    4106    40.7         Rural           Y
LP2983        Y             N    8072   253.4          City           Y
LP2984        Y             N    7583   187.6          City           Y
LP2990        N             Y    4583   133.2        Suburb           N

[600 rows x 6 columns]

In [48]:
loan_df = loan_df.rename(columns = new_columns)
loan_df

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N    4583   128.4         Rural           N
LP1005        Y             Y    3000    66.0          City           Y
LP1006        Y             N    2583   120.5          City           Y
LP1008        N             N    6000   141.4          City           Y
LP1011        Y             Y    5417   267.4          City           Y
...         ...           ...     ...     ...           ...         ...
LP2974        Y             N    3232   108.6         Rural           Y
LP2979        Y             N    4106    40.7         Rural           Y
LP2983        Y             N    8072   253.4          City           Y
LP2984        Y             N    7583   187.6          City           Y
LP2990        N             Y    4583   133.2        Suburb           N

[600 rows x 6 columns]

In [49]:
loan_df.dtypes

married              str
self_employed        str
income             int64
amount           float64
property_area        str
loan_status          str
dtype: object

In [51]:
####형변환
loan_df['income'].astype('float')

loan_id
LP1003    4583.0
LP1005    3000.0
LP1006    2583.0
LP1008    6000.0
LP1011    5417.0
           ...
LP2974    3232.0
LP2979    4106.0
LP2983    8072.0
LP2984    7583.0
LP2990    4583.0
Name: income, Length: 600, dtype: float64

In [54]:
loan_df['income'] = loan_df['income'].astype('float')
loan_df.dtypes

married              str
self_employed        str
income           float64
amount           float64
property_area        str
loan_status          str
dtype: object