In [31]:
import pandas as pd

loan_df = pd.read_csv("data/loan.csv")
loan_df

,loan_id,married_or_not,self_employed_or_not,applicant_income,loan_amount,property_area,loan_status
0,LP1003,Y,N,4583,128.4,Rural,N
1,LP1005,Y,Y,3000,66.0,City,Y
2,LP1006,Y,N,2583,120.5,City,Y
3,LP1008,N,N,6000,141.4,City,Y
4,LP1011,Y,Y,5417,267.4,City,Y
...,...,...,...,...,...,...,...
595,LP2974,Y,N,3232,108.6,Rural,Y
596,LP2979,Y,N,4106,40.7,Rural,Y
597,LP2983,Y,N,8072,253.4,City,Y
598,LP2984,Y,N,7583,187.6,City,Y
599,LP2990,N,Y,4583,133.2,Suburb,N

In [2]:
-5 - -10

5

In [32]:
##컬럼 이름 변경
new_columns = {'married_or_not': 'married',
               'self_employed_or_not': 'self_employed',
               'applicant_income': 'income',
               'loan_amount': 'amount'}
loan_df = loan_df.rename(columns= new_columns)

##인덱스 변경 
loan_df = loan_df.set_index('loan_id')
loan_df

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N    4583   128.4         Rural           N
LP1005        Y             Y    3000    66.0          City           Y
LP1006        Y             N    2583   120.5          City           Y
LP1008        N             N    6000   141.4          City           Y
LP1011        Y             Y    5417   267.4          City           Y
...         ...           ...     ...     ...           ...         ...
LP2974        Y             N    3232   108.6         Rural           Y
LP2979        Y             N    4106    40.7         Rural           Y
LP2983        Y             N    8072   253.4          City           Y
LP2984        Y             N    7583   187.6          City           Y
LP2990        N             Y    4583   133.2        Suburb           N

[600 rows x 6 columns]

In [ ]:
## Series --> key를 값고 있는 어레이
loan_df['amount']

loan_id
LP1003    128.4
LP1005     66.0
LP1006    120.5
LP1008    141.4
LP1011    267.4
          ...
LP2974    108.6
LP2979     40.7
LP2983    253.4
LP2984    187.6
LP2990    133.2
Name: amount, Length: 600, dtype: float64

In [12]:
loan_df['amount'].dtype

dtype('float64')

In [13]:
loan_df['amount'].describe()

count    589.000000
mean     146.971307
std       85.756442
min        9.200000
25%      100.700000
50%      128.000000
75%      168.300000
max      700.300000
Name: amount, dtype: float64

In [33]:
loan_df['self_employed'].describe()

count     568
unique      2
top         N
freq      488
Name: self_employed, dtype: object

In [34]:
loan_df['self_employed'].unique()

<ArrowStringArray>
['N', 'Y', nan]
Length: 3, dtype: str

In [35]:
loan_df['self_employed'].value_counts(dropna=False)

self_employed
N      488
Y       80
NaN     32
Name: count, dtype: int64

In [37]:
loan_df['self_employed'].value_counts(dropna=False, normalize=True)

self_employed
N      0.813333
Y      0.133333
NaN    0.053333
Name: proportion, dtype: float64

In [25]:
loan_df[['amount']] #--> 데이터 프레임 타임 --> 시리즈 메소드 사용 불가

         amount
loan_id
LP1003    128.4
LP1005     66.0
LP1006    120.5
LP1008    141.4
LP1011    267.4
...         ...
LP2974    108.6
LP2979     40.7
LP2983    253.4
LP2984    187.6
LP2990    133.2

[600 rows x 1 columns]

In [26]:
loan_df['property_area']

loan_id
LP1003     Rural
LP1005      City
LP1006      City
LP1008      City
LP1011      City
           ...
LP2974     Rural
LP2979     Rural
LP2983      City
LP2984      City
LP2990    Suburb
Name: property_area, Length: 600, dtype: str

In [29]:
loan_df['property_area'].value_counts(dropna=False, normalize=True)

property_area
Suburb    0.380000
City      0.328333
Rural     0.291667
Name: proportion, dtype: float64