In [1]:
import pandas as pd

loan_df = pd.read_csv('data/loan.csv')
loan_df = loan_df.set_index('loan_id')
new_columns = {'married_or_not': 'married',
               'self_employed_or_not': 'self_employed',
               'applicant_income': 'income',
               'loan_amount': 'amount'                
}
##컬럼 이름 변경
loan_df = loan_df.rename(columns=new_columns)
####income컬럼 형변환
loan_df['income'].astype('float')
loan_df

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N    4583   128.4         Rural           N
LP1005        Y             Y    3000    66.0          City           Y
LP1006        Y             N    2583   120.5          City           Y
LP1008        N             N    6000   141.4          City           Y
LP1011        Y             Y    5417   267.4          City           Y
...         ...           ...     ...     ...           ...         ...
LP2974        Y             N    3232   108.6         Rural           Y
LP2979        Y             N    4106    40.7         Rural           Y
LP2983        Y             N    8072   253.4          City           Y
LP2984        Y             N    7583   187.6          City           Y
LP2990        N             Y    4583   133.2        Suburb           N

[600 rows x 6 columns]

In [8]:
income_mean = loan_df['income'].mean()
df = loan_df.query("(married == 'Y') & (income > @income_mean) & (property_area not in ['City', 'Suburb'])") 
df

        married self_employed  income  amount property_area loan_status
loan_id
LP1401        Y             N   14583   185.6         Rural           Y
LP1421        Y             N    5568   175.9         Rural           N
LP1426        Y             N    5667   180.5         Rural           Y
LP1448        Y             N   23803   370.5         Rural           Y
LP1465        Y             N    6080   182.7         Rural           N
LP1541        Y             N    6000   160.2         Rural           Y
LP1647        Y             N    9328   188.5         Rural           Y
LP1715        Y             Y    5703   130.6         Rural           Y
LP1784        Y             N    5500   170.4         Rural           Y
LP1798        Y             N    5819   120.8         Rural           Y
LP1807        Y             Y    6250   108.6         Rural           Y
LP1859        Y             N   14683   304.8         Rural           N
LP1922        Y             N   20667     NaN         Rural           N
LP1998        Y             N    7667   185.0         Rural           Y
LP2008        Y             Y    5746   144.9         Rural           Y
LP2050        Y             Y   10000   155.9         Rural           N
LP2065        Y             N   15000   300.5         Rural           Y
LP2067        Y             Y    8666   376.4         Rural           N
LP2142        Y             Y    5500   105.1         Rural           N
LP2149        Y             N    8333   165.3         Rural           Y
LP2191        Y             N   19730   570.1         Rural           N
LP2201        Y             Y    9323   380.7         Rural           Y
LP2219        Y             N    8750   130.0         Rural           Y
LP2250        Y             N    5488   125.8         Rural           Y
LP2262        Y             N    9504   275.2         Rural           Y
LP2317        Y             N   81000   360.3         Rural           N
LP2328        Y             N    6096   218.5         Rural           N
LP2348        Y             N    5829   138.0         Rural           Y
LP2407        Y             Y    7142   138.9         Rural           Y
LP2409        Y             N    7901   181.0         Rural           Y
LP2424        Y             N    7333   175.2         Rural           Y
LP2527        Y             Y   16525   150.9         Rural           Y
LP2692        Y             Y    5677   100.4         Rural           Y
LP2693        Y             Y    7948   480.8         Rural           Y
LP2699        Y             Y   17500   400.8         Rural           Y
LP2740        Y             N    6417   157.1         Rural           Y
LP2778        Y             Y    6633     NaN         Rural           N
LP2820        Y             N    5923   211.5         Rural           Y
LP2941        Y             Y    6383   187.2         Rural           N
LP2945        Y             Y    9963   181.0         Rural           Y

In [ ]:
df = df.drop('LP2945')  # axis=0 x행에서 인덱스 LP1006,  axis='index'같은 의미
df = df.drop('married', axis=1) # 컬럼: married 삭제 ,  axis = 'columns' 같은 의미
df = df.drop(columns='self_employed') # 컬럼: self_employed 삭제
df

         income  amount property_area loan_status
loan_id
LP1401    14583   185.6         Rural           Y
LP1421     5568   175.9         Rural           N
LP1426     5667   180.5         Rural           Y
LP1448    23803   370.5         Rural           Y
LP1465     6080   182.7         Rural           N
LP1541     6000   160.2         Rural           Y
LP1647     9328   188.5         Rural           Y
LP1715     5703   130.6         Rural           Y
LP1784     5500   170.4         Rural           Y
LP1798     5819   120.8         Rural           Y
LP1807     6250   108.6         Rural           Y
LP1859    14683   304.8         Rural           N
LP1922    20667     NaN         Rural           N
LP1998     7667   185.0         Rural           Y
LP2008     5746   144.9         Rural           Y
LP2050    10000   155.9         Rural           N
LP2065    15000   300.5         Rural           Y
LP2067     8666   376.4         Rural           N
LP2142     5500   105.1         Rural           N
LP2149     8333   165.3         Rural           Y
LP2191    19730   570.1         Rural           N
LP2201     9323   380.7         Rural           Y
LP2219     8750   130.0         Rural           Y
LP2250     5488   125.8         Rural           Y
LP2262     9504   275.2         Rural           Y
LP2317    81000   360.3         Rural           N
LP2328     6096   218.5         Rural           N
LP2348     5829   138.0         Rural           Y
LP2407     7142   138.9         Rural           Y
LP2409     7901   181.0         Rural           Y
LP2424     7333   175.2         Rural           Y
LP2527    16525   150.9         Rural           Y
LP2692     5677   100.4         Rural           Y
LP2693     7948   480.8         Rural           Y
LP2699    17500   400.8         Rural           Y
LP2740     6417   157.1         Rural           Y
LP2778     6633     NaN         Rural           N
LP2820     5923   211.5         Rural           Y
LP2941     6383   187.2         Rural           N