In [5]:
import pandas as pd

airbnb_df = pd.read_csv('data/airbnb.csv')

airbnb_df.info()
airbnb_df.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 713 entries, 0 to 712
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             713 non-null    str
 1   state          713 non-null    str
 2   guests         713 non-null    int64
 3   beds           713 non-null    int64
 4   property_type  713 non-null    str
 5   rating         700 non-null    float64
 6   n_reviews      713 non-null    int64
 7   location       713 non-null    str
 8   price          713 non-null    int64
dtypes: float64(1), int64(4), str(4)
memory usage: 83.4 KB

np.int64(2)

In [17]:
print(airbnb_df.duplicated().sum())
airbnb_df[airbnb_df.duplicated()] #boolean값으로 인덱싱

2

,id,state,guests,beds,property_type,rating,n_reviews,location,price
493,UD8253,MASSACHUSETTS,3,1,Apartment,100.0,1,"Fenway/Kenmore, Boston.",124
496,UD8253,MASSACHUSETTS,3,1,Apartment,100.0,1,"Fenway/Kenmore, Boston.",124

In [20]:
#전체 중복값 삭제
airbnb_df.drop_duplicates()
airbnb_df = airbnb_df.drop_duplicates()

print(airbnb_df.duplicated().sum())

0

In [8]:
airbnb_df[airbnb_df.duplicated(subset='id')]

,id,state,guests,beds,property_type,rating,n_reviews,location,price
448,LN3479,California,2,2,Apartment,98.0,19,"East Hollywood, Los Angeles.",88
452,LN3479,California,2,2,Apartment,99.0,25,"East Hollywood, Los Angeles.",91
493,UD8253,MASSACHUSETTS,3,1,Apartment,100.0,1,"Fenway/Kenmore, Boston.",124
496,UD8253,MASSACHUSETTS,3,1,Apartment,100.0,1,"Fenway/Kenmore, Boston.",124
527,QO8555,California,7,4,House,80.0,1,"Excelsior, San Francisco.",199
601,BZ3596,Illinois,2,1,House,89.0,30,"Lakeview, Chicago.",119

In [10]:
airbnb_df[airbnb_df.duplicated(subset=['id','price' ]) ]

,id,state,guests,beds,property_type,rating,n_reviews,location,price
448,LN3479,California,2,2,Apartment,98.0,19,"East Hollywood, Los Angeles.",88
493,UD8253,MASSACHUSETTS,3,1,Apartment,100.0,1,"Fenway/Kenmore, Boston.",124
496,UD8253,MASSACHUSETTS,3,1,Apartment,100.0,1,"Fenway/Kenmore, Boston.",124
527,QO8555,California,7,4,House,80.0,1,"Excelsior, San Francisco.",199
601,BZ3596,Illinois,2,1,House,89.0,30,"Lakeview, Chicago.",119

In [ ]:
airbnb_df[airbnb_df.duplicated(subset='id', keep=False)]  ##keep = 'First'  첫번째는 유지 , keep=False 전체

,id,state,guests,beds,property_type,rating,n_reviews,location,price
6,LN3479,California,2,2,Apartment,96.0,15,"East Hollywood, Los Angeles.",88
201,UD8253,MASSACHUSETTS,3,1,Apartment,100.0,1,"Fenway/Kenmore, Boston.",124
273,QO8555,California,7,4,House,85.0,3,"Excelsior, San Francisco.",199
448,LN3479,California,2,2,Apartment,98.0,19,"East Hollywood, Los Angeles.",88
452,LN3479,California,2,2,Apartment,99.0,25,"East Hollywood, Los Angeles.",91
493,UD8253,MASSACHUSETTS,3,1,Apartment,100.0,1,"Fenway/Kenmore, Boston.",124
496,UD8253,MASSACHUSETTS,3,1,Apartment,100.0,1,"Fenway/Kenmore, Boston.",124
527,QO8555,California,7,4,House,80.0,1,"Excelsior, San Francisco.",199
541,BZ3596,Illinois,2,1,Apartment,91.0,28,"Lakeview, Chicago.",119
601,BZ3596,Illinois,2,1,House,89.0,30,"Lakeview, Chicago.",119

In [23]:
import pandas as pd
cellphone_df = pd.read_csv('data/cellphone.csv')

cellphone_df[cellphone_df.duplicated(keep=False)]

      brand                       name  size   price  battery  weight  year
18  samsung        Galaxy S22+ (256GB)  6.6"  1199.0     4500   195.0  2022
19  samsung        Galaxy S22+ (256GB)  6.6"  1199.0     4500   195.0  2022
22  samsung     Galaxy Z Fold4 (256GB)  7.6"  1998.7     4400   263.0  2022
23  samsung     Galaxy Z Fold4 (256GB)  7.6"  1998.7     4400   263.0  2022
55    apple  iPhone 12 Pro Max (128GB)  6.7"  1490.0     3687   228.0  2020
56    apple  iPhone 12 Pro Max (128GB)  6.7"  1490.0     3687   228.0  2020
57    apple  iPhone 12 Pro Max (128GB)  6.7"  1490.0     3687   228.0  2020

In [25]:
cellphone_df = cellphone_df.drop_duplicates()
cellphone_df[cellphone_df.duplicated(keep=False)]

Empty DataFrame
Columns: [brand, name, size, price, battery, weight, year]
Index: []