In [2]:
import pandas as pd

airbnb_df = pd.read_csv('data/airbnb.csv')

airbnb_df.info()
airbnb_df

<class 'pandas.DataFrame'>
RangeIndex: 713 entries, 0 to 712
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             713 non-null    str
 1   state          713 non-null    str
 2   guests         713 non-null    int64
 3   beds           713 non-null    int64
 4   property_type  713 non-null    str
 5   rating         700 non-null    float64
 6   n_reviews      713 non-null    int64
 7   location       713 non-null    str
 8   price          713 non-null    int64
dtypes: float64(1), int64(4), str(4)
memory usage: 83.4 KB

,id,state,guests,beds,property_type,rating,n_reviews,location,price
0,BF1406,Illinois,2,1,Apartment,96.0,55,"Avondale, Chicago.",48
1,DB7921,MASSACHUSETTS,4,1,Apartment,NaN,0,"South End, Boston.",115
2,OZ5857,ILLINOIS,4,3,Apartment,100.0,51,"Avondale, Chicago.",150
3,HY8797,california,2,1,Apartment,75.0,4,"SoMa, San Francisco.",125
4,VN7858,massachusetts,2,1,House,88.0,23,"West Roxbury, Boston.",64
...,...,...,...,...,...,...,...,...,...
708,XG3289,California,2,1,Apartment,97.0,60,"Venice, Los Angeles.",150
709,ZR5298,california,4,2,Apartment,93.0,3,"Mid-Wilshire, Los Angeles.",100
710,XZ5531,California,2,1,Bungalow,93.0,3,"Redondo Beach, Los Angeles.",100
711,EE8333,ILLINOIS,2,1,House,80.0,15,"Lakeview, Chicago.",115
712,AA6024,Massachusetts,3,1,Apartment,96.0,61,"East Boston, Boston.",115

In [3]:
airbnb_df.describe()

           guests        beds      rating   n_reviews        price
count  713.000000  713.000000  700.000000  713.000000   713.000000
mean     3.161290    1.608696   94.820000   35.040673   121.235624
std      1.865736    0.967031    6.175233   51.432101    96.660215
min      1.000000    1.000000   40.000000    0.000000    14.000000
25%      2.000000    1.000000   93.000000    4.000000    98.000000
50%      2.000000    1.000000   96.000000   16.000000   119.000000
75%      4.000000    2.000000   99.000000   45.000000   139.000000
max     16.000000    8.000000  100.000000  525.000000  1800.000000

In [9]:
q1 = airbnb_df['price'].quantile(0.25)
q3 = airbnb_df['price'].quantile(0.75)
iqr = q3 - q1
lower_limit = q1 - 1.5 * iqr
upper_limit = q3 + 1.5 * iqr

In [10]:
airbnb_df[airbnb_df['price'] < lower_limit]  #--> 가격이 너무 낮은 이상점 정보

,id,state,guests,beds,property_type,rating,n_reviews,location,price
13,HB7516,Illinois,1,1,Apartment,94.0,56,"Little Italy/UIC, Chicago.",14
43,IT4655,California,2,8,Hostel,91.0,27,"Westlake, Los Angeles.",14

In [11]:
airbnb_df[airbnb_df['price'] > upper_limit]  #--> 가격이 너무 높은 이상점 정보

,id,state,guests,beds,property_type,rating,n_reviews,location,price
91,FG7538,California,6,3,House,100.0,6,"Marina, San Francisco.",1800
442,ZL3688,California,16,8,Villa,92.0,7,"Malibu, Los Angeles.",1794

In [12]:
airbnb_df[ (airbnb_df['price'] < lower_limit) | (airbnb_df['price'] > upper_limit) ]

,id,state,guests,beds,property_type,rating,n_reviews,location,price
13,HB7516,Illinois,1,1,Apartment,94.0,56,"Little Italy/UIC, Chicago.",14
43,IT4655,California,2,8,Hostel,91.0,27,"Westlake, Los Angeles.",14
91,FG7538,California,6,3,House,100.0,6,"Marina, San Francisco.",1800
442,ZL3688,California,16,8,Villa,92.0,7,"Malibu, Los Angeles.",1794

In [14]:
## 이상점 처리 방법
# 1. 이상점 정보 삭제
# 2. 이상점 정보를 최저 또는 최고 limit 으로 변경
# 3. 이상점 정보를 제외하고, 정상치 정보만 취급
# 
#### 이상점 제외하고 정상 정보만 처리 방법 
condition1 = airbnb_df['price'] >= lower_limit
condition2 = airbnb_df['price'] <= upper_limit
airbnb_df[condition1 & condition2]

,id,state,guests,beds,property_type,rating,n_reviews,location,price
0,BF1406,Illinois,2,1,Apartment,96.0,55,"Avondale, Chicago.",48
1,DB7921,MASSACHUSETTS,4,1,Apartment,NaN,0,"South End, Boston.",115
2,OZ5857,ILLINOIS,4,3,Apartment,100.0,51,"Avondale, Chicago.",150
3,HY8797,california,2,1,Apartment,75.0,4,"SoMa, San Francisco.",125
4,VN7858,massachusetts,2,1,House,88.0,23,"West Roxbury, Boston.",64
...,...,...,...,...,...,...,...,...,...
708,XG3289,California,2,1,Apartment,97.0,60,"Venice, Los Angeles.",150
709,ZR5298,california,4,2,Apartment,93.0,3,"Mid-Wilshire, Los Angeles.",100
710,XZ5531,California,2,1,Bungalow,93.0,3,"Redondo Beach, Los Angeles.",100
711,EE8333,ILLINOIS,2,1,House,80.0,15,"Lakeview, Chicago.",115
712,AA6024,Massachusetts,3,1,Apartment,96.0,61,"East Boston, Boston.",115

In [ ]:
## 이상점을 제외한 정보만 다시 저장
airbnb_df = airbnb_df[condition1 & condition2] 
airbnb_df

,id,state,guests,beds,property_type,rating,n_reviews,location,price
0,BF1406,Illinois,2,1,Apartment,96.0,55,"Avondale, Chicago.",48
1,DB7921,MASSACHUSETTS,4,1,Apartment,NaN,0,"South End, Boston.",115
2,OZ5857,ILLINOIS,4,3,Apartment,100.0,51,"Avondale, Chicago.",150
3,HY8797,california,2,1,Apartment,75.0,4,"SoMa, San Francisco.",125
4,VN7858,massachusetts,2,1,House,88.0,23,"West Roxbury, Boston.",64
...,...,...,...,...,...,...,...,...,...
708,XG3289,California,2,1,Apartment,97.0,60,"Venice, Los Angeles.",150
709,ZR5298,california,4,2,Apartment,93.0,3,"Mid-Wilshire, Los Angeles.",100
710,XZ5531,California,2,1,Bungalow,93.0,3,"Redondo Beach, Los Angeles.",100
711,EE8333,ILLINOIS,2,1,House,80.0,15,"Lakeview, Chicago.",115
712,AA6024,Massachusetts,3,1,Apartment,96.0,61,"East Boston, Boston.",115