In [2]:
##효준이는 스마트폰 구매 후보에서 가격이 너무 싸거나 비싼 건 제외하려고 합니다. 
# cellphone_df에서 가격을 기준으로 이상점으로 볼 수 있는 데이터는 삭제해 주세요.

import pandas as pd
cellphone_df = pd.read_csv('data/cellphone.csv')
cellphone_df

,brand,name,size,price,battery,weight,year
0,apple,iPhone 14 (128GB),"6.1""",1250.0,3729,172.0,2022
1,apple,iPhone 14 (256GB),"6.1""",1400.0,3729,172.0,2022
2,Apple,iPhone 14 (512GB),"6.1""",1700.0,3729,172.0,2022
3,apple,iPhone 14 Plus (128GB),"6.7""",1350.0,4325,203.0,2022
4,APPLE,iPhone 14 Plus (256GB),"6.7""",1500.0,4325,203.0,2022
...,...,...,...,...,...,...,...
65,SAMSUNG,Galaxy S20 Ultra (512GB),"6.9""",1793.0,5000,220.0,2020
66,samsung,Galaxy S20+ (256GB),"6.7""",1353.0,4500,186.0,2020
67,SAMSUNG,Galaxy Z Flip2 (256GB),"6.7""",1650.0,3300,183.0,2020
68,Samsung,Galaxy Z Fold2 (256GB),"7.6""",1892.0,4500,282.0,2020
69,samsung,Galaxy Z Fold2 Thom Browne Edition (256GB),"7.6""",3960.0,4500,282.0,2020

In [7]:
q1 = cellphone_df['price'].quantile(0.25)
q3 = cellphone_df['price'].quantile(0.75)
iqr = q3 - q1
lower_limit = q1 - 1.5 * iqr
upper_limit = q3 + 1.5 * iqr
cellphone_df[(cellphone_df['price'] < lower_limit) | (cellphone_df['price'] > upper_limit)]

,brand,name,size,price,battery,weight,year
40,SAMSUNG,Galaxy A12 (32GB),"6.5""",275.0,5000,205.0,2021
48,samsung,Galaxy Z Fold3 Thom Browne Edition (512GB),"7.6""",3960.0,4400,271.0,2021
69,samsung,Galaxy Z Fold2 Thom Browne Edition (256GB),"7.6""",3960.0,4500,282.0,2020

In [8]:
mask = cellphone_df[(cellphone_df['price'] < lower_limit) | (cellphone_df['price'] > upper_limit)].index

In [9]:
cellphone_df.drop(mask)

      brand                      name  size   price  battery  weight  year
0     apple         iPhone 14 (128GB)  6.1"  1250.0     3729   172.0  2022
1     apple         iPhone 14 (256GB)  6.1"  1400.0     3729   172.0  2022
2     Apple         iPhone 14 (512GB)  6.1"  1700.0     3729   172.0  2022
3     apple    iPhone 14 Plus (128GB)  6.7"  1350.0     4325   203.0  2022
4     APPLE    iPhone 14 Plus (256GB)  6.7"  1500.0     4325   203.0  2022
..      ...                       ...   ...     ...      ...     ...   ...
64  samsung  Galaxy S20 Ultra (256GB)  6.9"  1595.0     5000   220.0  2020
65  SAMSUNG  Galaxy S20 Ultra (512GB)  6.9"  1793.0     5000   220.0  2020
66  samsung       Galaxy S20+ (256GB)  6.7"  1353.0     4500   186.0  2020
67  SAMSUNG    Galaxy Z Flip2 (256GB)  6.7"  1650.0     3300   183.0  2020
68  Samsung    Galaxy Z Fold2 (256GB)  7.6"  1892.0     4500   282.0  2020

[67 rows x 7 columns]

In [11]:
cellphone_df = cellphone_df.drop(mask)
cellphone_df

      brand                      name  size   price  battery  weight  year
0     apple         iPhone 14 (128GB)  6.1"  1250.0     3729   172.0  2022
1     apple         iPhone 14 (256GB)  6.1"  1400.0     3729   172.0  2022
2     Apple         iPhone 14 (512GB)  6.1"  1700.0     3729   172.0  2022
3     apple    iPhone 14 Plus (128GB)  6.7"  1350.0     4325   203.0  2022
4     APPLE    iPhone 14 Plus (256GB)  6.7"  1500.0     4325   203.0  2022
..      ...                       ...   ...     ...      ...     ...   ...
64  samsung  Galaxy S20 Ultra (256GB)  6.9"  1595.0     5000   220.0  2020
65  SAMSUNG  Galaxy S20 Ultra (512GB)  6.9"  1793.0     5000   220.0  2020
66  samsung       Galaxy S20+ (256GB)  6.7"  1353.0     4500   186.0  2020
67  SAMSUNG    Galaxy Z Flip2 (256GB)  6.7"  1650.0     3300   183.0  2020
68  Samsung    Galaxy Z Fold2 (256GB)  7.6"  1892.0     4500   282.0  2020

[67 rows x 7 columns]