## 효준이가 수집한 핸드폰 데이터를 좀 더 사용하기 좋게 전처리해 봅시다. 
아래에 쓰여 있는 대로 brand, name, size 컬럼에 있는 데이터를 가공해 주세요.
- brand 컬럼에 저장된 제조사명의 대소문자 표기를 통일해 주세요. 첫 글자는 대문자로, 나머지 글자는 소문자로 바꿔 주시면 됩니다.
- name 컬럼에는 iPhone 14 Pro (256GB)와 같이 스마트폰의 모델명(iPhone 14 Pro)과 용량(256GB) 정보가 함께 들어 있습니다. 
    모델과 용량을 쉽게 구분해서 볼 수 있도록 문자열을 분리해 주세요. 
    모델명은 model 컬럼, 용량은 capacity 컬럼에 저장하고, 기존의 name 컬럼은 삭제하면 됩니다. 
    모델명 앞뒤에 불필요한 공백 문자열이 없도록 처리하는 것도 잊지 마세요!
- size 컬럼에는 스마트폰의 디스플레이 크기 정보가 담겨 있습니다. 
    그런데 데이터에 인치(inch)를 나타내는 '"' 기호가 들어 있어서 pandas가 이 컬럼의 데이터 타입을 문자 데이터로 인식하고 있네요. 
    '"' 기호를 없앤 뒤 size 컬럼의 데이터 타입을 적절한 숫자 타입으로 바꿔 주세요.

In [4]:
import pandas as pd
cellphone_df = pd.read_csv('data/cellphone.csv')
cellphone_df

,brand,name,size,price,battery,weight,year
0,apple,iPhone 14 (128GB),"6.1""",1250.0,3729,172.0,2022
1,apple,iPhone 14 (256GB),"6.1""",1400.0,3729,172.0,2022
2,Apple,iPhone 14 (512GB),"6.1""",1700.0,3729,172.0,2022
3,apple,iPhone 14 Plus (128GB),"6.7""",1350.0,4325,203.0,2022
4,APPLE,iPhone 14 Plus (256GB),"6.7""",1500.0,4325,203.0,2022
...,...,...,...,...,...,...,...
65,SAMSUNG,Galaxy S20 Ultra (512GB),"6.9""",1793.0,5000,220.0,2020
66,samsung,Galaxy S20+ (256GB),"6.7""",1353.0,4500,186.0,2020
67,SAMSUNG,Galaxy Z Flip2 (256GB),"6.7""",1650.0,3300,183.0,2020
68,Samsung,Galaxy Z Fold2 (256GB),"7.6""",1892.0,4500,282.0,2020
69,samsung,Galaxy Z Fold2 Thom Browne Edition (256GB),"7.6""",3960.0,4500,282.0,2020

In [8]:
##cellphone_df['brand'] = cellphone_df['brand'].str.upper()
cellphone_df['brand'] = cellphone_df['brand'].str.capitalize()

In [19]:
cellphone_df['name'].str.split("(").str[0].str.strip()

0                              iPhone 14
1                              iPhone 14
2                              iPhone 14
3                         iPhone 14 Plus
4                         iPhone 14 Plus
                     ...
65                      Galaxy S20 Ultra
66                           Galaxy S20+
67                        Galaxy Z Flip2
68                        Galaxy Z Fold2
69    Galaxy Z Fold2 Thom Browne Edition
Name: name, Length: 70, dtype: object

In [ ]:
display(cellphone_df['name'].str.split("("))
cellphone_df['model'] = cellphone_df['name'].str.split("(").str[0].str.strip()
cellphone_df['capacity'] = cellphone_df['name'].str.split("(").str[1].str.replace(")", '', regex=False).str.strip()
cellphone_df

0                              [iPhone 14 , 128GB)]
1                              [iPhone 14 , 256GB)]
2                              [iPhone 14 , 512GB)]
3                         [iPhone 14 Plus , 128GB)]
4                         [iPhone 14 Plus , 256GB)]
                          ...
65                      [Galaxy S20 Ultra , 512GB)]
66                           [Galaxy S20+ , 256GB)]
67                        [Galaxy Z Flip2 , 256GB)]
68                        [Galaxy Z Fold2 , 256GB)]
69    [Galaxy Z Fold2 Thom Browne Edition , 256GB)]
Name: name, Length: 70, dtype: object

,brand,name,size,price,battery,weight,year,model,capacity
0,Apple,iPhone 14 (128GB),"6.1""",1250.0,3729,172.0,2022,iPhone 14,128GB
1,Apple,iPhone 14 (256GB),"6.1""",1400.0,3729,172.0,2022,iPhone 14,256GB
2,Apple,iPhone 14 (512GB),"6.1""",1700.0,3729,172.0,2022,iPhone 14,512GB
3,Apple,iPhone 14 Plus (128GB),"6.7""",1350.0,4325,203.0,2022,iPhone 14 Plus,128GB
4,Apple,iPhone 14 Plus (256GB),"6.7""",1500.0,4325,203.0,2022,iPhone 14 Plus,256GB
...,...,...,...,...,...,...,...,...,...
65,Samsung,Galaxy S20 Ultra (512GB),"6.9""",1793.0,5000,220.0,2020,Galaxy S20 Ultra,512GB
66,Samsung,Galaxy S20+ (256GB),"6.7""",1353.0,4500,186.0,2020,Galaxy S20+,256GB
67,Samsung,Galaxy Z Flip2 (256GB),"6.7""",1650.0,3300,183.0,2020,Galaxy Z Flip2,256GB
68,Samsung,Galaxy Z Fold2 (256GB),"7.6""",1892.0,4500,282.0,2020,Galaxy Z Fold2,256GB
69,Samsung,Galaxy Z Fold2 Thom Browne Edition (256GB),"7.6""",3960.0,4500,282.0,2020,Galaxy Z Fold2 Thom Browne Edition,256GB

In [21]:
cellphone_df = cellphone_df.drop(columns='name')
cellphone_df

,brand,size,price,battery,weight,year,model,capacity
0,Apple,"6.1""",1250.0,3729,172.0,2022,iPhone 14,128GB
1,Apple,"6.1""",1400.0,3729,172.0,2022,iPhone 14,256GB
2,Apple,"6.1""",1700.0,3729,172.0,2022,iPhone 14,512GB
3,Apple,"6.7""",1350.0,4325,203.0,2022,iPhone 14 Plus,128GB
4,Apple,"6.7""",1500.0,4325,203.0,2022,iPhone 14 Plus,256GB
...,...,...,...,...,...,...,...,...
65,Samsung,"6.9""",1793.0,5000,220.0,2020,Galaxy S20 Ultra,512GB
66,Samsung,"6.7""",1353.0,4500,186.0,2020,Galaxy S20+,256GB
67,Samsung,"6.7""",1650.0,3300,183.0,2020,Galaxy Z Flip2,256GB
68,Samsung,"7.6""",1892.0,4500,282.0,2020,Galaxy Z Fold2,256GB
69,Samsung,"7.6""",3960.0,4500,282.0,2020,Galaxy Z Fold2 Thom Browne Edition,256GB

In [ ]:
cellphone_df['size'] = cellphone_df['size'].str.replace('"', '', regex=False).str.strip()
cellphone_df['size']

0     6.1
1     6.1
2     6.1
3     6.7
4     6.7
     ...
65    6.9
66    6.7
67    6.7
68    7.6
69    7.6
Name: size, Length: 70, dtype: str

In [26]:
cellphone_df['size'] = cellphone_df['size'].astype(float)
cellphone_df['size']

0     6.1
1     6.1
2     6.1
3     6.7
4     6.7
     ...
65    6.9
66    6.7
67    6.7
68    7.6
69    7.6
Name: size, Length: 70, dtype: float64

In [ ]:
### 정담 ######

# 대소문자 표기 통일하기
cellphone_df['brand'] = cellphone_df['brand'].str.capitalize()

# 문자열 분리하기
cellphone_df['model'] = cellphone_df['name'].str.split('(').str[0]
cellphone_df['capacity'] = cellphone_df['name'].str.split('(').str[1]

# 불필요한 문자 제거하기
cellphone_df['model'] = cellphone_df['model'].str.strip()
cellphone_df['capacity'] = cellphone_df['capacity'].str.replace(')', '', regex=False)

# 기존 컬럼 삭제하기
cellphone_df = cellphone_df.drop(columns='name')

# 불필요한 문자 제거하고 데이터 타입 변경하기
cellphone_df['size'] = cellphone_df['size'].str.replace('"', '', regex=False).astype('float')
cellphone_df