## pandas의 cut() 함수를 사용해서 사람들의 연령대를 분류해 봤습니다. 
이번 시간에는 apply() 라는 함수에 대해 알아보고, 이 함수를 가지고 똑같은 작업을 다시 해 볼 건데요. 

cut()이 데이터 구간화를 위해 만들어진 함수라면, 
apply()는 원하는 기능을 마음대로 구현할 수 있는 만능 함수라고 할 수 있어요.

일단 apply()는 다른 함수를 아규먼트로 사용합니다. apply가 '적용하다'라는 뜻을 가지고 있는 것처럼 DataFrame이나 Series에 있는 값 하나하나에 아규먼트로 받은 함수를 적용해 주는데요.

In [1]:
import pandas as pd

df = pd.DataFrame([[1, 9], [4, 16]], columns=['column1', 'column2'])
df

   column1  column2
0        1        9
1        4       16

여기서 column2에 있는 9와 16의 제곱근 값을 각각 구해 볼게요. 이때 제곱근을 계산해 주는 numpy의 sqrt()라는 함수를 사용할 건데요. 아래와 같이 sqrt() 안에 9라는 값을 넘겨주면 9의 제곱근인 3.0을 리턴합니다.

In [2]:
import numpy as np

np.sqrt(9)  # 출력 내용 -> 3.0

np.float64(3.0)

이제 sqrt()를 apply()와 함께 사용해 볼게요. column2에 있는 값들의 제곱근을 구할 거니까, 아래와 같이 df['column2'].apply()라고 써 준 뒤 괄호 안에는 numpy의 sqrt() 함수를 넣어 주면 됩니다.

In [3]:
df['column2'].apply(np.sqrt)

0    3.0
1    4.0
Name: column2, dtype: float64

여기서 주의할 점은, 함수 안에 함수를 넘겨줄 때에는 함수의 이름까지만 쓰고 뒤에 괄호를 쓰지 않아야 한다는 건데요. 그러니까 np.sqrt라고 써야지 np.sqrt()라고 쓰면 안 된다는 거죠. 위 코드를 실행하면 아래 보이는 것처럼 3과 4, 즉 9와 16의 제곱근 값을 담고 있는 Series가 나옵니다.

## apply()로 데이터 구간화하기

In [4]:
patient_df = pd.read_csv('data/patient.csv')
patient_df.head()

   age     sex  glucose  cholesterol  height  weight  hip  waist diabetes
0   50    Male      385          140    1.75    78.0   41     37        Y
1   37  Female       67          214    1.63    65.8   42     34        N
2   43  Female      100          160    1.63    63.5   40     37        N
3   32  Female       90          176    1.60   114.3   58     45        N
4   20    Male       71          164    1.83    65.8   36     29        N

In [5]:
def group_age(x):
    if x >= 10 and x < 20:
        return '10s'
    elif x >= 20 and x < 30:
        return '20s'
    elif x >= 30 and x < 40:
        return '30s'
    elif x >= 40 and x < 50:
        return '40s'
    elif x >= 50 and x < 60:
        return '50s'
    else:
        return '60s'

patient_df['age_group'] = patient_df['age'].apply(group_age)
patient_df

,age,sex,glucose,cholesterol,height,weight,hip,waist,diabetes,age_group
0,50,Male,385,140,1.75,78.0,41,37,Y,50s
1,37,Female,67,214,1.63,65.8,42,34,N,30s
2,43,Female,100,160,1.63,63.5,40,37,N,40s
3,32,Female,90,176,1.60,114.3,58,45,N,30s
4,20,Male,71,164,1.83,65.8,36,29,N,20s
...,...,...,...,...,...,...,...,...,...,...
343,40,Male,87,218,1.85,90.7,41,38,N,40s
344,66,Male,174,188,1.73,95.3,48,45,N,60s
345,31,Female,69,183,1.68,86.2,47,41,N,30s
346,44,Male,84,202,1.73,71.2,37,33,N,40s
347,40,Female,85,169,1.65,81.6,44,40,N,40s

## lambda (람다) 함수와 apply()

마지막으로 한 가지만 더 알아 볼게요. apply()는 람다 함수라는 특이한 형태의 함수와 함께 사용하기도 하는데요. 람다 함수는 def라는 키워드를 사용해서 함수를 따로 정의할 필요 없이, 다른 함수 안에서 바로 사용할 수 있습니다. 따로 이름이 없다는 뜻으로 '익명 함수(Anonymous Function)'이라고 부르기도 하죠.

In [6]:
def multiply_two(x):
    return 2*x

In [7]:
lambda x: 2*x

이제 apply()와 람다 함수를 함께 사용해 볼게요. patient_df의 height 컬럼에는 미터 기준 키 정보가 들어 있었는데요. 표기 단위를 미터에서 인치로 바꾸고 싶다면, 1미터는 약 39.370079인치니까 height 값에 39.370079를 곱해 주면 되겠죠? 아래와 같은 코드를 통해, apply()로 Series에 있는 값들에 하나씩 접근해서 람다 함수를 적용할 수 있어요.

In [8]:
patient_df['height'].apply(lambda x: 39.370079*x)

0      68.897638
1      64.173229
2      64.173229
3      62.992126
4      72.047245
         ...
343    72.834646
344    68.110237
345    66.141733
346    68.110237
347    64.960630
Name: height, Length: 348, dtype: float64

방금 전에는 람다 함수의 기본 사용법을 알아보기 위해 엄청 간단한 코드를 예로 들었는데요. 사실 이런 경우에는 굳이 람다 함수를 사용할 필요 없이 아래 코드처럼 직접 컬럼에 사칙연산을 적용하는 것이 좋습니다. 코드도 좀 더 간결하고 실행 속도도 더 빠르기 때문이죠.

In [9]:
patient_df['height'] * 39.370079

0      68.897638
1      64.173229
2      64.173229
3      62.992126
4      72.047245
         ...
343    72.834646
344    68.110237
345    66.141733
346    68.110237
347    64.960630
Name: height, Length: 348, dtype: float64

그리고 if문을 함께 사용하면 람다 함수를 좀 더 유용하게 사용할 수 있습니다. 예를 들어 아래와 같이 bmi라는 컬럼에 BMI 값을 계산해 두고, BMI 값이 30이 넘으면 비만('Y'), 넘지 않으면 비만이 아니라고('N') 구분한다고 할게요. 그러려면 콜론 뒤에 바로 조건식이 참일 때 리턴할 값인 Y를 써 주고, if문을 쓴 다음에는 else 뒤에 조건식이 거짓일 때 리턴할 값인 N을 써 주면 됩니다.

In [11]:
patient_df['bmi'] = round(patient_df['weight'] / patient_df['height']**2, 1)
print(patient_df['bmi'])
patient_df['bmi'].apply(lambda x: 'Y' if x > 30 else 'N')

0      25.5
1      24.8
2      23.9
3      44.6
4      19.6
       ...
343    26.5
344    31.8
345    30.5
346    23.8
347    30.0
Name: bmi, Length: 348, dtype: float64

0      N
1      N
2      N
3      Y
4      N
      ..
343    N
344    Y
345    Y
346    N
347    N
Name: bmi, Length: 348, dtype: str