## 실습 설명
익중이는 배달 전문 음식점을 운영하고 있습니다. 다행히 맛집으로 소문이 났는지, 저녁 시간대에 들어오는 주문이 엄청 많아져서 새로운 배달 업체와 계약을 했다고 하네요. 일주일 정도 서비스를 이용해 본 뒤, 배달이 빠르게 잘 되고 있는지 배달 수수료로 얼마를 내고 있는지 등을 전반적으로 확인해 보려고 하는데요.

일단 이 업체를 이용하기 시작한 날인 2022년 10월 17일의 데이터만 뽑아서 확인해 봅시다. 주문 시각(order_time)을 기준으로 데이터를 추출해 보세요!

In [1]:
import pandas as pd

delivery_df = pd.read_csv('data/delivery.csv')
delivery_df

              order_time  distance  time_taken  num_of_deliveries  charge
0    2022-10-17 18:34:00       3.9          21                  1    4.68
1    2022-10-17 18:35:00       5.2          24                  1    7.02
2    2022-10-17 18:36:00       8.4          36                  2    9.53
3    2022-10-17 18:37:00       3.6          17                  1    6.21
4    2022-10-17 18:41:00       2.6          15                  1    2.44
..                   ...       ...         ...                ...     ...
104  2022-10-23 19:28:00       6.4          37                  1    5.01
105  2022-10-23 19:28:00       3.9          26                  2    7.34
106  2022-10-23 19:48:00       3.3          21                  1    3.83
107  2022-10-23 19:49:00       5.8          22                  1    5.80
108  2022-10-23 19:50:00       4.4          19                  1    7.78

[109 rows x 5 columns]

In [2]:
delivery_df.dtypes

order_time               str
distance             float64
time_taken             int64
num_of_deliveries      int64
charge               float64
dtype: object

In [5]:
delivery_df['order_time'] = pd.to_datetime(delivery_df['order_time'])

In [9]:
delivery_df = delivery_df.set_index('order_time')
delivery_df

                     distance  time_taken  num_of_deliveries  charge
order_time
2022-10-17 18:34:00       3.9          21                  1    4.68
2022-10-17 18:35:00       5.2          24                  1    7.02
2022-10-17 18:36:00       8.4          36                  2    9.53
2022-10-17 18:37:00       3.6          17                  1    6.21
2022-10-17 18:41:00       2.6          15                  1    2.44
...                       ...         ...                ...     ...
2022-10-23 19:28:00       6.4          37                  1    5.01
2022-10-23 19:28:00       3.9          26                  2    7.34
2022-10-23 19:48:00       3.3          21                  1    3.83
2022-10-23 19:49:00       5.8          22                  1    5.80
2022-10-23 19:50:00       4.4          19                  1    7.78

[109 rows x 4 columns]

In [10]:
delivery_df.loc['2022-10-17']

                     distance  time_taken  num_of_deliveries  charge
order_time
2022-10-17 18:34:00       3.9          21                  1    4.68
2022-10-17 18:35:00       5.2          24                  1    7.02
2022-10-17 18:36:00       8.4          36                  2    9.53
2022-10-17 18:37:00       3.6          17                  1    6.21
2022-10-17 18:41:00       2.6          15                  1    2.44
2022-10-17 18:54:00      15.2          34                  1   13.72
2022-10-17 18:54:00       2.4          14                  1    2.00
2022-10-17 18:54:00      13.7          50                  2    8.74
2022-10-17 18:55:00       7.6          28                  1    5.52
2022-10-17 18:55:00       3.3          16                  1    6.95
2022-10-17 19:16:00       4.7          19                  1    3.54
2022-10-17 19:17:00      12.5          43                  2   14.34
2022-10-17 19:17:00       3.0          16                  1    3.42
2022-10-17 19:19:00       8.5          30                  1   10.30
2022-10-17 19:20:00       5.2          22                  1    3.09
2022-10-17 19:21:00       2.1          14                  1    3.00
2022-10-17 19:21:00      16.5          52                  2   13.78
2022-10-17 19:22:00       8.3          30                  2   13.86